 <header> 
    <div class="brand-name">
        <h3>SwiftLaundry</h3>
    </div>
    
    <div class="logout-area">
        <a href="#" class="logout-button">Logout</a>
        <span>USER</span>
    </div>
</header>

<nav>
    <a href="dashboard_overview.php"><i class="far fa-chart-bar"></i><span>Overview</span></a>
    <a href="dashboard_items.php"><i class="fas fa-dolly-flatbed"></i><span>Items</span></a>
    <a href="dashboard_receipts.php"><i class="fas fa-receipt"></i><span>Receipts</span></a>
    <a href="dashboard_tickets.php"><i class="fas fa-ticket-alt"></i><span>Tickets</span></a>
    <a href="dashboard_reports.php"><i class="fas fa-clipboard-list"></i><span>Reports</span></a>
</nav>